-- Security hardening — run in Supabase SQL editor (or via supabase db push)
-- Generated by security audit 2026-08-21

-- M3: Stored-XSS defense at the DB level.
-- Client-side validateURL() only runs in dialogs; direct REST calls
-- with a valid session could insert javascript:/data: URIs.
-- This constraint makes protocol whitelisting unconditional.
ALTER TABLE public.bookmarks
    DROP CONSTRAINT IF EXISTS bookmark_url_protocol_check;

ALTER TABLE public.bookmarks
    ADD CONSTRAINT bookmark_url_protocol_check
    CHECK (bookmark_url ~* '^https?://');

-- H1 backstop: verify RLS is ENABLED and per-user on both tables.
-- Run this to audit current state:
--   select tablename, rowsecurity from pg_tables where schemaname = 'public';
--
-- If RLS is off, enable it and add per-user policies:
--
-- ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.folders   ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY "users_own_bookmarks" ON public.bookmarks
--     FOR ALL USING (auth.uid() = bookmark_user_id);
--
-- CREATE POLICY "users_own_folders" ON public.folders
--     FOR ALL USING (auth.uid() = folder_user_id);
